var SimpleMDE = SimpleMDE || {};
SimpleMDE.translations = {
	"URL for the link:": "URL для посилання:",
	"URL of the image:": "URL зображення:",
	"Bold": "Жирний",
	"Italic": "Курсив",
	"Strikethrough": "Закреслений",
	"Heading": "Заголовок",
	"Smaller Heading": "Меньший заголовок",
	"Bigger Heading": "Більший заголовок",
	"Heading 1": "Заголовок 1",
	"Heading 2": "Заголовок 2",
	"Heading 3": "Заголовок 3",
	"Code": "Код",
	"Quote": "Цитата",
	"Generic List": "Ненумерованний список",
	"Numbered List": "Нумерованний список",
	"Clean block": "Очистити блок",
	"Create Link": "Вставити посилання",
	"Insert Image": "Вставити зображення",
	"Insert Table": "Вставити таблицю",
	"Insert Horizontal Line": "Вставити горизонтальну лінію",
	"Toggle Preview": "Переключити попередній перегляд",
	"Toggle Side by Side": "Редактирование и просмотр",
	"Toggle Fullscreen": "Переключити повноекранний режим",
	"Undo": "Відмінити",
	"Redo": "Повторити",
	"Lines:": "Стрічок:",
	"Words:": "Слів:"
};